services:
  frontend:
    build: frontend/.
    ports:
      - "3002:3002"
    env_file:
      - ./.env
    networks:
      - frontend

  backend:
    build: backend/.
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    depends_on:
      - database
    networks:
      - frontend
      - backend

  database:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - backend

networks:
  frontend:
    driver: bridge

  backend:
    driver: bridge
